version: '3.3'
services:
  csgo:
    container_name: csgo
    network_mode: host
    volumes:
      - ./data:/home
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - TZ=Europe/Rome
      - PUID=1000
      - GUID=1000
    image: csgo:blast
